// Export formats. Phase 1 ships Markdown + JSON; PDF and the speaker manifest
// arrive in Phase 3.

import type { Session } from '@/lib/types';
import { getModel } from '@/config/models';
import { getPersona } from '@/lib/personas';
import { FORMATS } from '@/lib/formats';

export const DISCLOSURE_FOOTER =
  'This transcript was generated by AI language models participating as fictional characters. It is not a record of statements by any person.';

function rosterLines(session: Session): string[] {
  const lines = session.config.agents.map((a) => {
    const persona = getPersona(a.personaId);
    const model = getModel(a.modelId);
    return `- ${a.displayName} — ${persona?.name ?? a.personaId} — ${
      model?.displayName ?? a.modelId
    }`;
  });
  const modModel = getModel(session.config.moderator.modelId);
  lines.push(
    `- ${session.config.moderator.displayName || 'Moderator'} — (moderator) — ${
      modModel?.displayName ?? session.config.moderator.modelId
    }`,
  );
  return lines;
}

export function toMarkdown(session: Session): string {
  const { config } = session;
  const date = session.createdAt.slice(0, 10);
  const formatLabel = FORMATS[config.format]?.label ?? config.format;

  const header = [
    `# ${config.title}`,
    '',
    `**Topic:** ${config.topic}`,
    `**Date:** ${date}  ·  **Format:** ${formatLabel}  ·  **Participants:** ${config.agentCount}`,
    '',
    '## Roster',
    ...rosterLines(session),
    '',
    '---',
    '',
  ].join('\n');

  const body = session.turns
    .map((t) => `**${t.speakerDisplayName.toUpperCase()}**\n\n${t.text}`)
    .join('\n\n');

  const footer = ['', '', '---', '', `_${DISCLOSURE_FOOTER}_`].join('\n');

  return header + body + footer;
}

export function toJson(session: Session): string {
  return JSON.stringify(session, null, 2);
}

/** Speaker manifest (PRD §11.4) — Phase 3, but cheap and useful now. */
export function toSpeakerManifest(session: Session): string {
  const { config } = session;
  const date = session.createdAt.slice(0, 10);
  const formatLabel = FORMATS[config.format]?.label ?? config.format;
  const lines = [
    `Session: "${config.title}"`,
    `Date: ${date} · Format: ${formatLabel} · ${config.agentCount} participants`,
    '',
    ...config.agents.map((a) => {
      const persona = getPersona(a.personaId);
      const model = getModel(a.modelId);
      return `${a.displayName.padEnd(10)}${(persona?.name ?? '').padEnd(20)}${
        model?.displayName ?? a.modelId
      }`;
    }),
    `${(config.moderator.displayName || 'Moderator').padEnd(10)}${'—'.padEnd(20)}${
      getModel(config.moderator.modelId)?.displayName ??
      config.moderator.modelId
    }`,
  ];
  return lines.join('\n');
}
