// Export formats. Phase 1 ships Markdown + JSON; PDF and the speaker manifest
// arrive in Phase 3.

import type { Session } from '@/lib/types';
import { getModel } from '@/config/models';
import { getPersona } from '@/lib/personas';
import { FORMATS } from '@/lib/formats';

export const DISCLOSURE_FOOTER =
  'This transcript was generated by AI language models participating as fictional characters. It is not a record of statements by any person.';

function rosterLines(session: Session): string[] {
  const lines = session.config.agents.map((a) => {
    const persona = getPersona(a.personaId);
    const model = getModel(a.modelId);
    return `- ${a.displayName} — ${persona?.name ?? a.personaId} — ${
      model?.displayName ?? a.modelId
    }`;
  });
  const modModel = getModel(session.config.moderator.modelId);
  lines.push(
    `- ${session.config.moderator.displayName || 'Moderator'} — (moderator) — ${
      modModel?.displayName ?? session.config.moderator.modelId
    }`,
  );
  return lines;
}

export function toMarkdown(session: Session): string {
  const { config } = session;
  const date = session.createdAt.slice(0, 10);
  const formatLabel = FORMATS[config.format]?.label ?? config.format;

  const header = [
    `# ${config.title}`,
    '',
    `**Topic:** ${config.topic}`,
    `**Date:** ${date}  ·  **Format:** ${formatLabel}  ·  **Participants:** ${config.agentCount}`,
    '',
    '## Roster',
    ...rosterLines(session),
    '',
    '---',
    '',
  ].join('\n');

  const body = session.turns
    .map((t) => `**${t.speakerDisplayName.toUpperCase()}**\n\n${t.text}`)
    .join('\n\n');

  const footer = ['', '', '---', '', `_${DISCLOSURE_FOOTER}_`].join('\n');

  return header + body + footer;
}

export function toJson(session: Session): string {
  return JSON.stringify(session, null, 2);
}

/**
 * ElevenLabs script export (B-4). An ordered array shaped for the Create /
 * Stream dialogue endpoints: one entry per turn with speaker, voiceId, and the
 * tagged text (falling back to plain text where no voice pass ran). Voice ids
 * come from each speaker's config.
 */
export function toElevenLabsScript(session: Session): string {
  const { config } = session;
  const voiceFor = (speakerId: string): string | undefined => {
    if (speakerId === 'moderator') return config.moderator.voiceId;
    return config.agents.find((a) => a.id === speakerId)?.voiceId;
  };

  const dialogue = session.turns.map((t) => ({
    speaker: t.speakerDisplayName,
    voiceId: voiceFor(t.speakerId) ?? null,
    text: t.taggedText ?? t.text,
  }));

  return JSON.stringify(
    {
      title: config.title,
      // v3 audio tags only register on Creative or Natural stability. Robust
      // ignores directional prompts. Do not use SSML <break> tags (unsupported).
      stability: 'Creative or Natural (Robust ignores tags)',
      note: 'Audio tags register only at Creative/Natural stability. No SSML break tags — v3 does not support them.',
      dialogue,
    },
    null,
    2,
  );
}

/** Speaker manifest (PRD §11.4) — Phase 3, but cheap and useful now. */
export function toSpeakerManifest(session: Session): string {
  const { config } = session;
  const date = session.createdAt.slice(0, 10);
  const formatLabel = FORMATS[config.format]?.label ?? config.format;
  const lines = [
    `Session: "${config.title}"`,
    `Date: ${date} · Format: ${formatLabel} · ${config.agentCount} participants`,
    '',
    ...config.agents.map((a) => {
      const persona = getPersona(a.personaId);
      const model = getModel(a.modelId);
      const base = `${a.displayName.padEnd(10)}${(persona?.name ?? '').padEnd(20)}${(
        model?.displayName ?? a.modelId
      ).padEnd(24)}`;
      return a.referenceImage ? `${base}${a.referenceImage}` : base.trimEnd();
    }),
    `${(config.moderator.displayName || 'Moderator').padEnd(10)}${'—'.padEnd(20)}${
      getModel(config.moderator.modelId)?.displayName ??
      config.moderator.modelId
    }`,
  ];
  return lines.join('\n');
}
